#!/usr/bin/env bash
# Tests for scripts/deploy-review.sh --status flag and CLI parsing
# Run via: bash tests/test_deploy_review.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$SCRIPT_DIR/scripts/deploy-review.sh"

PASS=0
FAIL=0

assert_eq() {
    local label="$1" expected="$2" actual="$3"
    if [[ "$expected" == "$actual" ]]; then
        echo "  PASS  $label"
        PASS=$((PASS + 1))
    else
        echo "  FAIL  $label"
        echo "        expected: '$expected'"
        echo "        actual:   '$actual'"
        FAIL=$((FAIL + 1))
    fi
}

assert_contains() {
    local label="$1" needle="$2" haystack="$3"
    if [[ "$haystack" == *"$needle"* ]]; then
        echo "  PASS  $label"
        PASS=$((PASS + 1))
    else
        echo "  FAIL  $label"
        echo "        expected to contain: '$needle'"
        echo "        actual: '$haystack'"
        FAIL=$((FAIL + 1))
    fi
}

assert_not_contains() {
    local label="$1" needle="$2" haystack="$3"
    if [[ "$haystack" != *"$needle"* ]]; then
        echo "  PASS  $label"
        PASS=$((PASS + 1))
    else
        echo "  FAIL  $label"
        echo "        expected NOT to contain: '$needle'"
        echo "        actual: '$haystack'"
        FAIL=$((FAIL + 1))
    fi
}

echo "=== tests/test_deploy_review.sh ==="

# ── --help flag ────────────────────────────────────────────────────────────
echo ""
echo "--- --help flag ---"

HELP_OUTPUT="$(bash "$SCRIPT" --help 2>&1)" || true
HELP_EXIT=$?
assert_eq "--help exits 0" "0" "$HELP_EXIT"
assert_contains "--help mentions --status" "--status" "$HELP_OUTPUT"
assert_contains "--help mentions --all" "--all" "$HELP_OUTPUT"
assert_contains "--help mentions --dry-run" "--dry-run" "$HELP_OUTPUT"
assert_contains "--help shows status description" "Show last review results" "$HELP_OUTPUT"

# ── Missing PR number ─────────────────────────────────────────────────────
echo ""
echo "--- missing PR number ---"

MISSING_EXIT=0
MISSING_OUTPUT="$(bash "$SCRIPT" 2>&1)" || MISSING_EXIT=$?
assert_eq "no args exits non-zero" "1" "$MISSING_EXIT"
assert_contains "no args shows error" "PR number is required" "$MISSING_OUTPUT"

# ── --status without PR number ─────────────────────────────────────────────
echo ""
echo "--- --status without PR number ---"

STATUS_NO_PR_EXIT=0
STATUS_NO_PR="$(bash "$SCRIPT" --status 2>&1)" || STATUS_NO_PR_EXIT=$?
assert_eq "--status without PR exits non-zero" "1" "$STATUS_NO_PR_EXIT"
assert_contains "--status without PR shows error" "PR number is required" "$STATUS_NO_PR"

# ── Non-numeric PR number ──────────────────────────────────────────────────
echo ""
echo "--- non-numeric PR number ---"

NON_NUMERIC_EXIT=0
NON_NUMERIC="$(bash "$SCRIPT" --status abc 2>&1)" || NON_NUMERIC_EXIT=$?
assert_eq "non-numeric PR exits non-zero" "1" "$NON_NUMERIC_EXIT"
assert_contains "non-numeric PR shows error" "PR number must be numeric" "$NON_NUMERIC"

# ── --status with valid PR (requires gh, may skip) ─────────────────────────
echo ""
echo "--- --status with valid PR (gh-dependent) ---"

if command -v gh &>/dev/null && gh auth status &>/dev/null 2>&1; then
    # Use a known non-existent PR to test the NO_REVIEW / error path
    # PR 999999 is unlikely to exist
    STATUS_OUTPUT="$(bash "$SCRIPT" --status 999999 2>&1)" || true
    STATUS_EXIT=$?
    # Should either show NO_REVIEW or an error about the PR not existing
    if [[ "$STATUS_OUTPUT" == *"NO_REVIEW"* ]] || [[ "$STATUS_OUTPUT" == *"Error"* ]]; then
        echo "  PASS  --status 999999 handles missing PR gracefully"
        PASS=$((PASS + 1))
    else
        echo "  FAIL  --status 999999 unexpected output"
        echo "        actual: '$STATUS_OUTPUT'"
        FAIL=$((FAIL + 1))
    fi
else
    echo "  SKIP  gh CLI not authenticated — skipping live status tests"
fi

# ── show_status function parsing (unit test via mock) ──────────────────────
echo ""
echo "--- show_status body parsing ---"

# Create a temporary script that sources the function and tests parsing
TMPDIR_TEST="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_TEST"' EXIT

# Mock gh to return a known review comment
cat > "$TMPDIR_TEST/gh" <<'MOCK_GH'
#!/usr/bin/env bash
# Mock gh that returns a canned review comment
if [[ "$*" == *"--comments"* ]]; then
    cat <<'JSON'
{"createdAt":"2026-04-06T10:30:00Z","body":"## Automated Safety Review — PR #362\n\n**Review agents:** review-memory-safety review-security\n**Test agents:** test-unit\n**Date:** 2026-04-06\n\n---\n\n# Safety Review Findings\n\n### review-memory-safety\n\nP2: Potential use-after-move in tracker.cpp:45\nP3: Missing const on parameter in fusion.h:22\n\n### review-security\n\nP2: Unchecked input size in parser.cpp:88\n\n# Test Verification Results\n\n### test-unit\n\nAll 1259 tests passed.\n\n---\n_Generated by deploy-review.sh — 2 reviewers + 1 test agents_"}
JSON
    exit 0
fi
echo "unexpected gh call: $*" >&2
exit 1
MOCK_GH
chmod +x "$TMPDIR_TEST/gh"

# Run --status with mock gh
MOCK_OUTPUT="$(PATH="$TMPDIR_TEST:$PATH" bash "$SCRIPT" --status 362 2>&1)" || true
MOCK_EXIT=$?

assert_eq "mock --status exits 0" "0" "$MOCK_EXIT"
assert_contains "shows PR number" "PR #362" "$MOCK_OUTPUT"
assert_contains "shows review date" "2026-04-06" "$MOCK_OUTPUT"
assert_contains "shows reviewers" "review-memory-safety" "$MOCK_OUTPUT"
assert_contains "shows reviewers (security)" "review-security" "$MOCK_OUTPUT"
assert_contains "shows testers" "test-unit" "$MOCK_OUTPUT"
assert_contains "shows P2 count" "P2" "$MOCK_OUTPUT"
assert_contains "shows P3 count" "P3" "$MOCK_OUTPUT"
assert_contains "shows status" "NEEDS_FIX" "$MOCK_OUTPUT"
assert_not_contains "does not show PASS" "PASS" "$MOCK_OUTPUT"

# ── Test NO_REVIEW path ───────────────────────────────────────────────────
echo ""
echo "--- NO_REVIEW path ---"

# Mock gh returning no matching comments
cat > "$TMPDIR_TEST/gh" <<'MOCK_GH_EMPTY'
#!/usr/bin/env bash
if [[ "$*" == *"--comments"* ]]; then
    # gh --jq with no matching comments produces empty output
    exit 0
fi
echo "unexpected gh call: $*" >&2
exit 1
MOCK_GH_EMPTY
chmod +x "$TMPDIR_TEST/gh"

NO_REVIEW_OUTPUT="$(PATH="$TMPDIR_TEST:$PATH" bash "$SCRIPT" --status 999 2>&1)" || true
NO_REVIEW_EXIT=$?

assert_eq "no-review exits 0" "0" "$NO_REVIEW_EXIT"
assert_contains "shows NO_REVIEW" "NO_REVIEW" "$NO_REVIEW_OUTPUT"

# ── Test PASS status (no P1/P2) ───────────────────────────────────────────
echo ""
echo "--- PASS status path ---"

cat > "$TMPDIR_TEST/gh" <<'MOCK_GH_PASS'
#!/usr/bin/env bash
if [[ "$*" == *"--comments"* ]]; then
    cat <<'JSON'
{"createdAt":"2026-04-07T08:00:00Z","body":"## Automated Safety Review — PR #100\n\n**Review agents:** review-memory-safety review-security\n**Test agents:** test-unit test-scenario\n**Date:** 2026-04-07\n\n---\n\n# Safety Review Findings\n\n### review-memory-safety\n\nNo issues found.\n\n### review-security\n\nP3: Minor logging of internal paths\nP4: Consider adding rate limiting\n\n# Test Verification Results\n\n### test-unit\n\nAll 1259 tests passed.\n\n### test-scenario\n\nAll scenarios passed.\n\n---\n_Generated by deploy-review.sh — 2 reviewers + 2 test agents_"}
JSON
    exit 0
fi
echo "unexpected gh call: $*" >&2
exit 1
MOCK_GH_PASS
chmod +x "$TMPDIR_TEST/gh"

PASS_OUTPUT="$(PATH="$TMPDIR_TEST:$PATH" bash "$SCRIPT" --status 100 2>&1)" || true
PASS_EXIT=$?

assert_eq "pass-status exits 0" "0" "$PASS_EXIT"
assert_contains "shows PASS status" "PASS" "$PASS_OUTPUT"
assert_contains "shows testers (scenario)" "test-scenario" "$PASS_OUTPUT"
assert_contains "shows 0 P1" "0 P1" "$PASS_OUTPUT"
assert_contains "shows 0 P2" "0 P2" "$PASS_OUTPUT"

# ── Summary ────────────────────────────────────────────────────────────────
echo ""
echo "=== Results: $PASS passed, $FAIL failed ==="

if [[ "$FAIL" -gt 0 ]]; then
    exit 1
fi
exit 0
