// common/ipc/include/ipc/message_bus_factory.h
// IPC backend selection helper.
//
// Selects and constructs the appropriate message bus backend based on a
// simple string parameter:
//   - "shm"   → ShmMessageBus   (POSIX shared memory, always available)
//   - "zenoh" → ZenohMessageBus (requires -DENABLE_ZENOH=ON at build time)
//
// Usage:
//   #include "ipc/message_bus_factory.h"
//
//   // Create a bus variant using the desired backend (defaults to "shm"):
//   auto bus = drone::ipc::create_message_bus("shm");
//
//   // Example: advertise/subscribe through whichever backend is active.
//   auto pub = drone::ipc::bus_advertise<MyMsg>(bus, "telemetry");
//   auto sub = drone::ipc::bus_subscribe<MyMsg>(bus, "telemetry");
//
//   // Service channels (Zenoh only):
//   auto client = drone::ipc::bus_create_client<Req, Resp>(bus, "my_service");
//   auto server = drone::ipc::bus_create_server<Req, Resp>(bus, "my_service");
//
// Since ShmMessageBus and ZenohMessageBus are concrete (non-virtual)
// template factories, we can't return a single polymorphic pointer.
// Instead we return a std::variant<...> (MessageBusVariant) plus helpers.
#pragma once

#include "ipc/iservice_channel.h"
#include "ipc/shm_message_bus.h"

#ifdef HAVE_ZENOH
#include "ipc/zenoh_message_bus.h"
#include "ipc/zenoh_network_config.h"
#include "ipc/zenoh_session.h"
#endif

#include <memory>
#include <string>
#include <type_traits>
#include <variant>

#include <spdlog/spdlog.h>

namespace drone::ipc {

/// Holds exactly one of the two message bus backends.
/// Processes use visit() or if-else to call advertise/subscribe.
using MessageBusVariant = std::variant<std::unique_ptr<ShmMessageBus>
#ifdef HAVE_ZENOH
                                       ,
                                       std::unique_ptr<ZenohMessageBus>
#endif
                                       >;

/// Create the IPC message bus, optionally applying config.
/// @param backend  "shm" (default) or "zenoh".
/// @param shm_pool_mb  Zenoh SHM pool size in MB (0 = use default 32 MB).
///                     Parsed from config/default.json "zenoh.shm_pool_size_mb".
/// @param zenoh_config_json  Optional raw Zenoh JSON config string.
///                           If non-empty, passed to ZenohSession::configure().
///                           Typically generated by ZenohNetworkConfig::to_json().
inline MessageBusVariant create_message_bus(const std::string& backend           = "shm",
                                            std::size_t        shm_pool_mb       = 0,
                                            const std::string& zenoh_config_json = "") {
    (void)shm_pool_mb;  // used only when HAVE_ZENOH is defined
    (void)zenoh_config_json;
#ifdef HAVE_ZENOH
    if (backend == "zenoh") {
        if (!zenoh_config_json.empty()) {
            drone::ipc::ZenohSession::instance().configure(zenoh_config_json);
            drone::ipc::ZenohSession::instance().set_network_enabled(true);
        }
        if (shm_pool_mb > 0) {
            drone::ipc::ZenohSession::instance().configure_shm(shm_pool_mb * 1024 * 1024);
        }
        spdlog::info("[MessageBusFactory] Selected backend: Zenoh");
        return std::make_unique<ZenohMessageBus>();
    }
#else
    if (backend == "zenoh") {
        spdlog::warn("[MessageBusFactory] Zenoh requested but not compiled in "
                     "(HAVE_ZENOH not defined) — falling back to SHM");
    }
#endif
    spdlog::info("[MessageBusFactory] Selected backend: POSIX SHM");
    return std::make_unique<ShmMessageBus>();
}

/// Config-aware overload: reads ipc_backend, zenoh.shm_pool_size_mb, and
/// zenoh.network from the application config object.
///
/// @tparam ConfigT  Any type with get<T>(key, default) and section(key)
///                  methods (e.g. drone::Config).
///
/// Usage:
///   drone::Config cfg;
///   cfg.load("config/default.json");
///   auto bus = drone::ipc::create_message_bus(cfg);
template<typename ConfigT,
         typename = typename std::enable_if<!std::is_convertible<ConfigT, std::string>::value>::type>
MessageBusVariant create_message_bus(const ConfigT& cfg) {
    const auto backend     = cfg.template get<std::string>("ipc_backend", "shm");
    const auto shm_pool_mb = cfg.template get<std::size_t>("zenoh.shm_pool_size_mb", 0);

    std::string zenoh_json;
#ifdef HAVE_ZENOH
    if (backend == "zenoh" && cfg.template get<bool>("zenoh.network.enabled", false)) {
        auto net_cfg = ZenohNetworkConfig::from_app_config(cfg.section("zenoh.network"));
        zenoh_json   = net_cfg.to_json();
    }
#endif

    return create_message_bus(backend, shm_pool_mb, zenoh_json);
}

// ─────────────────────────────────────────────────────────────
// Helper: advertise / subscribe through the variant
// ─────────────────────────────────────────────────────────────

/// Create a publisher through whichever bus is active.
template<typename T>
std::unique_ptr<IPublisher<T>> bus_advertise(MessageBusVariant& bus, const std::string& topic) {
    return std::visit(
        [&](auto& b) -> std::unique_ptr<IPublisher<T>> { return b->template advertise<T>(topic); },
        bus);
}

/// Create a subscriber through whichever bus is active.
template<typename T>
std::unique_ptr<ISubscriber<T>> bus_subscribe(MessageBusVariant& bus, const std::string& topic,
                                              int max_retries = 50, int retry_ms = 200) {
    return std::visit(
        [&](auto& b) -> std::unique_ptr<ISubscriber<T>> {
            return b->template subscribe<T>(topic, max_retries, retry_ms);
        },
        bus);
}

/// Create an optional/lazy subscriber (single attempt, no retries).
/// Equivalent to subscribe() with max_retries=0.
/// For SHM: tries once to open the segment — is_connected() may return false
///          if the publisher hasn't created the shared-memory segment yet.
/// For Zenoh: the underlying Zenoh session always accepts the subscription
///            (is_connected() returns true) because pub/sub discovery is
///            asynchronous; messages will arrive once a publisher appears.
/// Use for optional channels where it's OK if no publisher exists yet.
template<typename T>
std::unique_ptr<ISubscriber<T>> bus_subscribe_optional(MessageBusVariant& bus,
                                                       const std::string& topic) {
    return bus_subscribe<T>(bus, topic, 0, 0);
}

// ─────────────────────────────────────────────────────────────
// Helper: service client / server through the variant
// ─────────────────────────────────────────────────────────────

/// Create a service client through whichever bus is active.
/// @note Service channels are only available on the Zenoh backend.
///       SHM backend returns nullptr with a warning.
template<typename Req, typename Resp>
std::unique_ptr<IServiceClient<Req, Resp>> bus_create_client(MessageBusVariant& bus,
                                                             const std::string& service,
                                                             uint64_t           timeout_ms = 5000) {
    return std::visit(
        [&](auto& b) -> std::unique_ptr<IServiceClient<Req, Resp>> {
#ifdef HAVE_ZENOH
            using BusType = std::decay_t<decltype(*b)>;
            if constexpr (std::is_same_v<BusType, ZenohMessageBus>) {
                return b->template create_client<Req, Resp>(service, timeout_ms);
            }
#endif
            (void)b;
            (void)service;
            (void)timeout_ms;
            spdlog::warn("[MessageBusFactory] Service channels are not available "
                         "on the SHM backend");
            return nullptr;
        },
        bus);
}

/// Create a service server through whichever bus is active.
/// @note Service channels are only available on the Zenoh backend.
///       SHM backend returns nullptr with a warning.
template<typename Req, typename Resp>
std::unique_ptr<IServiceServer<Req, Resp>> bus_create_server(MessageBusVariant& bus,
                                                             const std::string& service) {
    return std::visit(
        [&](auto& b) -> std::unique_ptr<IServiceServer<Req, Resp>> {
#ifdef HAVE_ZENOH
            using BusType = std::decay_t<decltype(*b)>;
            if constexpr (std::is_same_v<BusType, ZenohMessageBus>) {
                return b->template create_server<Req, Resp>(service);
            }
#endif
            (void)b;
            (void)service;
            spdlog::warn("[MessageBusFactory] Service channels are not available "
                         "on the SHM backend");
            return nullptr;
        },
        bus);
}

}  // namespace drone::ipc
